apiVersion: v1
kind: Namespace
metadata:
  name: nginx-demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-blue
  namespace: nginx-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Production - Blue Environment</title>
        <style>
            body { font-family: Arial; text-align: center; padding: 50px; background: #667eea; color: white; }
            .container { background: rgba(255,255,255,0.1); padding: 30px; border-radius: 10px; }
            h1 { font-size: 48px; margin: 20px 0; }
            .badge { display: inline-block; padding: 10px 20px; background: #4299e1; border-radius: 20px; margin: 5px; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🔵 BLUE - PRODUCTION</h1>
            <p>This is the active production environment</p>
            <div class="badge">Active</div>
            <div class="badge">Stable</div>
            <p style="margin-top: 30px; font-family: monospace; font-size: 12px;">Git: 7c0714c6f7cac16d4ec78d730f8c29d40901f268</p>
        </div>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-green
  namespace: nginx-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Preview - Green Environment</title>
        <style>
            body { font-family: Arial; text-align: center; padding: 50px; background: #11998e; color: white; }
            .container { background: rgba(255,255,255,0.1); padding: 30px; border-radius: 10px; }
            h1 { font-size: 48px; margin: 20px 0; }
            .badge { display: inline-block; padding: 10px 20px; background: #48bb78; border-radius: 20px; margin: 5px; }
            .pulse { animation: pulse 2s infinite; }
            @keyframes pulse { 0%, 100% { transform: scale(1); } 50% { transform: scale(1.05); } }
        </style>
    </head>
    <body>
        <div class="container">
            <h1 class="pulse">🟢 GREEN - PREVIEW</h1>
            <p>This is the preview environment for testing</p>
            <div class="badge">Preview</div>
            <div class="badge">Awaiting Promotion</div>
            <p style="margin-top: 30px; font-family: monospace; font-size: 12px;">Git: {{GIT_HASH}}</p>
        </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  namespace: nginx-demo
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: nginx-demo
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-preview
  namespace: nginx-demo
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: nginx-demo
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-demo
  namespace: nginx-demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300  # Auto-rollback after 5 minutes if not progressing
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
        version: blue
    spec:
      containers:
      - name: nginx
        image: 416716292256.dkr.ecr.us-west-2.amazonaws.com/nginx-demo-app:7c0714c6f7cac16d4ec78d730f8c29d40901f268
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 25m
            memory: 32Mi
      volumes:
      - name: html
        configMap:
          name: nginx-blue
  strategy:
    blueGreen:
      activeService: nginx-demo
      previewService: nginx-demo-preview
      autoPromotionEnabled: false  # Manual promotion for demo
      scaleDownDelaySeconds: 30
      # Analysis is optional - comment out for simpler demo
      # prePromotionAnalysis:
      #   templates:
      #   - templateName: nginx-simple-health-check
      # postPromotionAnalysis:
      #   templates:
      #   - templateName: nginx-post-promotion-check
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-demo
  namespace: nginx-demo
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-demo
            port:
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-demo-preview
  namespace: nginx-demo
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-demo-preview
            port:
              name: http

