apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.blueGreen.activeService }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nginx-demo.labels" . | nindent 4 }}
    service-type: active
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "nginx-demo.selectorLabels" . | nindent 4 }}

